version: "3.9"

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mailing_s

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - mailing_s

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - mailing_s

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION_ID=3
    container_name: app
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      - MAIL_DRIVER=&MAIL_DRIVER
      - MAIL_HOST=&MAIL_HOST
      - MAIL_PORT=&MAIL_PORT
      - MAIL_USERNAME=&MAIL_USERNAME
      - MAIL_PASSWORD=&MAIL_PASSWORD
      - MAIL_ENCRYPTION=&MAIL_ENCRYPTION
      - elasticsearch.address=localhost:9200
    depends_on:
      - elasticsearch
    networks:
      - mailing_s

networks:
  mailing_s:
    driver: bridge